/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Driver */

#ifndef _Included_Driver
#define _Included_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Driver
 * Method:    sec
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Driver_sec
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
